import type { Book } from "../../type/Book";

const img = (seed: string) => `https://picsum.photos/seed/${seed}/400/400`;

export const mockBooks: Book[] = [
  {
    authors: [{ id: 1, name: "Nguyễn Văn A", slug: "nguyen-van-a" }],
    book_cover: null,
    categories: { id: 10, name: "Sách Công nghệ", is_leaf: true },
    current_seller: {
      id: 101,
      sku: "PY-001",
      name: "TechStore",
      link: "https://example.com/py",
      logo: "https://picsum.photos/seed/logo1/64/64",
      price: 110000,
      product_id: "p1",
      store_id: 1001,
      is_best_store: true,
      is_offline_installment_supported: null,
    },
    description:
      "Cuốn sách giới thiệu toàn diện về lập trình Python cơ bản, kèm ví dụ dễ hiểu và bài tập thực hành.",
    images: [
      {
        base_url: img("py1"),
        is_gallery: false,
        label: null,
        large_url: img("py1"),
        medium_url: img("py1"),
        position: 1,
        small_url: img("py1"),
        thumbnail_url: img("py1"),
      },
    ],
    list_price: 150000,
    name: "Lập trình Python cơ bản",
    original_price: 150000,
    quantity_sold: { text: "Đã bán 1k+", value: 1200 },
    rating_average: 4.5,
    short_description: "Học Python từ con số 0 với ví dụ rõ ràng.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "320" },
        ],
      },
    ],
  },
  {
    authors: [{ id: 2, name: "Trần B", slug: "tran-b" }],
    book_cover: null,
    categories: { id: 11, name: "Lập trình Web", is_leaf: true },
    current_seller: {
      id: 102,
      sku: "JS-001",
      name: "FrontendShop",
      link: "https://example.com/js",
      logo: "https://picsum.photos/seed/logo2/64/64",
      price: 135000,
      product_id: "p2",
      store_id: 1002,
      is_best_store: false,
      is_offline_installment_supported: null,
    },
    description:
      "Nội dung chuyên sâu về JavaScript nâng cao, tối ưu hiệu năng và patterns hiện đại.",
    images: [
      {
        base_url: img("js1"),
        is_gallery: false,
        label: null,
        large_url: img("js1"),
        medium_url: img("js1"),
        position: 1,
        small_url: img("js1"),
        thumbnail_url: img("js1"),
      },
    ],
    list_price: 180000,
    name: "Học JavaScript nâng cao",
    original_price: 180000,
    quantity_sold: { text: "Đã bán 500+", value: 560 },
    rating_average: 4.2,
    short_description: "JS nâng cao, tối ưu và best practices.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "280" },
        ],
      },
    ],
  },
  {
    authors: [{ id: 3, name: "Lê C", slug: "le-c" }],
    book_cover: null,
    categories: { id: 12, name: "Thuật toán", is_leaf: true },
    current_seller: {
      id: 103,
      sku: "ALGO-001",
      name: "AlgoBooks",
      link: "https://example.com/algo",
      logo: "https://picsum.photos/seed/logo3/64/64",
      price: 199000,
      product_id: "p3",
      store_id: 1003,
      is_best_store: true,
      is_offline_installment_supported: null,
    },
    description:
      "Giải thích chi tiết về thuật toán và cấu trúc dữ liệu, kèm bài tập phỏng vấn.",
    images: [
      {
        base_url: img("algo1"),
        is_gallery: false,
        label: null,
        large_url: img("algo1"),
        medium_url: img("algo1"),
        position: 1,
        small_url: img("algo1"),
        thumbnail_url: img("algo1"),
      },
    ],
    list_price: 250000,
    name: "Thuật toán và cấu trúc dữ liệu",
    original_price: 250000,
    quantity_sold: { text: "Đã bán 2k+", value: 2100 },
    rating_average: 4.8,
    short_description: "Thuật toán, cấu trúc dữ liệu, bài tập.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "500" },
        ],
      },
    ],
  },
  {
    authors: [{ id: 4, name: "Phạm D", slug: "pham-d" }],
    book_cover: null,
    categories: { id: 13, name: "AI/ML", is_leaf: true },
    current_seller: {
      id: 104,
      sku: "ML-001",
      name: "AIBooks",
      link: "https://example.com/ml",
      logo: "https://picsum.photos/seed/logo4/64/64",
      price: 220000,
      product_id: "p4",
      store_id: 1004,
      is_best_store: false,
      is_offline_installment_supported: null,
    },
    description:
      "Machine Learning căn bản, trực quan, phù hợp người mới bắt đầu.",
    images: [
      {
        base_url: img("ml1"),
        is_gallery: false,
        label: null,
        large_url: img("ml1"),
        medium_url: img("ml1"),
        position: 1,
        small_url: img("ml1"),
        thumbnail_url: img("ml1"),
      },
    ],
    list_price: 260000,
    name: "Machine Learning căn bản",
    original_price: 260000,
    quantity_sold: { text: "Đã bán 800+", value: 840 },
    rating_average: 4.3,
    short_description: "Nhập môn machine learning cho người mới.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "350" },
        ],
      },
    ],
  },
  {
    authors: [{ id: 5, name: "Vũ E", slug: "vu-e" }],
    book_cover: null,
    categories: { id: 20, name: "Nấu ăn", is_leaf: true },
    current_seller: {
      id: 105,
      sku: "COOK-001",
      name: "KitchenHouse",
      link: "https://example.com/cook",
      logo: "https://picsum.photos/seed/logo5/64/64",
      price: 89000,
      product_id: "p5",
      store_id: 1005,
      is_best_store: false,
      is_offline_installment_supported: null,
    },
    description:
      "Bí quyết nấu ăn gia đình ngon miệng, dễ làm mỗi ngày.",
    images: [
      {
        base_url: img("cook1"),
        is_gallery: false,
        label: null,
        large_url: img("cook1"),
        medium_url: img("cook1"),
        position: 1,
        small_url: img("cook1"),
        thumbnail_url: img("cook1"),
      },
    ],
    list_price: 120000,
    name: "Nấu ăn cùng mẹ",
    original_price: 120000,
    quantity_sold: { text: "Đã bán 300+", value: 320 },
    rating_average: 4.0,
    short_description: "Món ngon dễ làm cho gia đình.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "200" },
        ],
      },
    ],
  },
  {
    authors: [{ id: 6, name: "Đặng F", slug: "dang-f" }],
    book_cover: null,
    categories: { id: 21, name: "Du lịch", is_leaf: true },
    current_seller: {
      id: 106,
      sku: "TRAVEL-001",
      name: "OutdoorLife",
      link: "https://example.com/travel",
      logo: "https://picsum.photos/seed/logo6/64/64",
      price: 99000,
      product_id: "p6",
      store_id: 1006,
      is_best_store: false,
      is_offline_installment_supported: null,
    },
    description:
      "Cẩm nang dã ngoại cuối tuần: địa điểm, chuẩn bị và mẹo an toàn.",
    images: [
      {
        base_url: img("travel1"),
        is_gallery: false,
        label: null,
        large_url: img("travel1"),
        medium_url: img("travel1"),
        position: 1,
        small_url: img("travel1"),
        thumbnail_url: img("travel1"),
      },
    ],
    list_price: 140000,
    name: "Dã ngoại cuối tuần",
    original_price: 140000,
    quantity_sold: { text: "Đã bán 150+", value: 160 },
    rating_average: 3.9,
    short_description: "Cẩm nang dã ngoại cho gia đình trẻ.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "180" },
        ],
      },
    ],
  },
  {
    authors: [{ id: 7, name: "Hồ G", slug: "ho-g" }],
    book_cover: null,
    categories: { id: 22, name: "Kỹ năng sống", is_leaf: true },
    current_seller: {
      id: 107,
      sku: "MIN-001",
      name: "LifeBooks",
      link: "https://example.com/minimal",
      logo: "https://picsum.photos/seed/logo7/64/64",
      price: 125000,
      product_id: "p7",
      store_id: 1007,
      is_best_store: false,
      is_offline_installment_supported: null,
    },
    description:
      "Sống tối giản để hạnh phúc hơn: dọn dẹp vật chất lẫn tinh thần.",
    images: [
      {
        base_url: img("min1"),
        is_gallery: false,
        label: null,
        large_url: img("min1"),
        medium_url: img("min1"),
        position: 1,
        small_url: img("min1"),
        thumbnail_url: img("min1"),
      },
    ],
    list_price: 160000,
    name: "Sống tối giản",
    original_price: 160000,
    quantity_sold: { text: "Đã bán 900+", value: 920 },
    rating_average: 4.6,
    short_description: "Tối giản để sống hạnh phúc.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "240" },
        ],
      },
    ],
  },
  {
    authors: [{ id: 8, name: "Bùi H", slug: "bui-h" }],
    book_cover: null,
    categories: { id: 23, name: "Kinh tế", is_leaf: true },
    current_seller: {
      id: 108,
      sku: "MICRO-001",
      name: "EconStore",
      link: "https://example.com/micro",
      logo: "https://picsum.photos/seed/logo8/64/64",
      price: 175000,
      product_id: "p8",
      store_id: 1008,
      is_best_store: false,
      is_offline_installment_supported: null,
    },
    description:
      "Kinh tế học vi mô căn bản, nhiều ví dụ minh hoạ dễ hiểu cho người mới.",
    images: [
      {
        base_url: img("micro1"),
        is_gallery: false,
        label: null,
        large_url: img("micro1"),
        medium_url: img("micro1"),
        position: 1,
        small_url: img("micro1"),
        thumbnail_url: img("micro1"),
      },
    ],
    list_price: 210000,
    name: "Kinh tế học vi mô",
    original_price: 210000,
    quantity_sold: { text: "Đã bán 700+", value: 750 },
    rating_average: 4.1,
    short_description: "Nhập môn kinh tế vi mô.",
    specifications: [
      {
        name: "Thông tin chung",
        attributes: [
          { code: "lang", name: "Ngôn ngữ", value: "Tiếng Việt" },
          { code: "pages", name: "Số trang", value: "300" },
        ],
      },
    ],
  },
];
